### ISSUE TITLE
no flag of Kosovo

### ISSUE THREAD

**Issue by sashagar** [stefangabos/world_countries#3]

**Comment by stefangabos** [comment]
I added the flag of Kosovo but not also added Kosovo to the list of countries. This is due to the fact that the International Organization for Standardization have not yet assigned an official code for Kosovo. Nevertheless, a temporary *XK* code is being used temporarily by the European Commission, the IMF, SWIFT, CLDR and other organizations.

**Comment by scrnjakovic** [comment]
It would be good to refrain from politics and wishes and follow standards instead, otherwise this will become opinion-based list and there would be a whole bunch of other **territories** that should be added as countries.
