### ISSUE TITLE
Add french polynesia country code 

### ISSUE THREAD

**Issue by gaetansenn** [stefangabos/world_countries#80]
Hello, 

I wanted to find french polynesia country but couldn't find it in the list :

https://countrycode.org/frenchpolynesia

Do you know if it's possible to add it ? I can do a PR for simplicity but need your confirmation first.

**Comment by stefangabos** [comment]
since french polynesia is not a "country" you can find it in the `world` file where you can find all administrative regions in the world. 
in the `countries` file you will find [sovereign states](https://en.wikipedia.org/wiki/List_of_sovereign_states) (the regions to which we refer to as _countries_)

**Comment by gaetansenn** [comment]
Ok i see thank you for you quick reply :)
